### ISSUE TITLE
Updated patches for Asterisk 11 and 13/master

### ISSUE THREAD

**Issue by ipoddubny** [pascomnet/asterisk_sbr#1]
Hi! I've cleaned up your patch a little (compilation warnings, formatting, C++ style comments) and applied to the current Asterisk 11 and master branches.
- [11](https://github.com/ipoddubny/asterisk/commit/fd7afdd811e8bf58a47844e32e8f73fecce7ba2c)
- [master](https://github.com/ipoddubny/asterisk/commit/35a585267a5273e688496561a3203709d37507c3)

member->call_pending was [recently removed](https://github.com/asterisk/asterisk/commit/30ab21d5fa42ef1412e0dede665eda7c77784627) in 11/13/master, that's why I had to remove it from the lua table to make it work.

I don't really know how to submit these patches as a pull request, that's why I'm posting it here as an issue.

**Comment by lichtzeichner** [comment]
Hi! Thanks for your help! Unfortunately our maintainer of this patch, @towe75 is on vacation right now. But we will look into integrating it as soon as he comes back.

**Comment by ludovic-gasc** [comment]
I've a suggestion: Maybe we could fork https://github.com/asterisk/asterisk, create a branch, and apply the patch ?
It will be easier to propose the patch to asterisk dev team via gerrit.

Have a nice day.

**Comment by towe75** [comment]
Hi, 
@GMLudo : yep, actually ipoddubny prepared this already.
Thank you @ipoddubny, your help is very welcome! Please submit a pull request towards our asterisk/asterisk fork, if possible.

What to do about the documentation? We could keep the asterisk_sbr repo for this purpose, also we could add some example scripts like GMLudo suggested to me at kamailio-world.

**Comment by ipoddubny** [comment]
Are you going to use original branches 11/13/master for the patched version or you'll create new branches to keep them apart to make it simpler and easier to pull new changes from the upstream?

I think it would be nicer to take the commits from my fork and re-create them with proper messages and original authors, doing something like this:

```
git remote add ipoddubny git@github.com:ipoddubny/asterisk.git
git fetch ipoddubny
git checkout -b app_queue_lua_11 11
git cherry-pick -n ipoddubny/app_queue_lua_11
git commit ;  write a good commit message...
git checkout -b app_queue_lua_13 13
git cherry-pick -n ipoddubny/app_queue_lua
git commit -C app_queue_lua_11  ; use the same message and author as the previous commit
git checkout -b app_queue_lua master
git cherry-pick -n ipoddubny/app_queue_lua
git commit -C app_queue_lua_11 ; same message again
git push origin app_queue_lua_11 app_queue_lua_13 app_queue_lua   ; origin = github:pascomnet/asterisk
git remote remove ipoddubny
```

Then you'll have 3 branches with clean history that you can use as a base for further improvements, and when you think the patch is ready for mainstream just rebase and squash the changes and send them to gerrit.

**Comment by towe75** [comment]
Using separate branches is the better option.  I'll prepare the repo after my vacation. 
What about my point regarding documentation/examples?

**Comment by ipoddubny** [comment]
> What to do about the documentation? We could keep the asterisk_sbr repo for this purpose, also we could add some example scripts like GMLudo suggested to me at kamailio-world.

👍 Totally reasonable, in my opinion.

**Comment by towe75** [comment]
I forked https://github.com/pascomnet/asterisk and created the 3 branches app_queue_lua (for master), app_queue_lua_13, app_queue_lua_11.

For now we will not submit the patch to gerrit. We are working on several enhancements ATM. Also Matt Jordan explained to me that we should come up with some automated tests to prove that a script is loaded, initialized, unloaded.

I will cleanup this repo and keep it for documentation & examples.

@ipoddubny : thank you again for helping!

**Comment by ludovic-gasc** [comment]
@towe75 Thanks a lot for the new repository: easier to us to follow the difference with Asterisk repository.
I strongly vote for examples.
Maybe, when you have some examples and finish the clean-up, you could post on asterisk-dev ML.
You should have more reactions than on Jira/Gerrit at the first stage.
