### ISSUE TITLE
Need to add get_vars() function

### ISSUE THREAD

**Issue by romkazor** [pascomnet/asterisk_sbr#4]
Hello, is there any way to read asterisk channel vars? If no, how about to add get_var()/get_vars() function in luascript? Thanks.

**Comment by towe75** [comment]
Hi @romkazor,

channel variables are readily parsed into a lua table and exposed to the callback functions. 
See README:

In enter_queue() and is_our_turn(): 

> entry.variables is a table with all channel variables of the enqueued entry

In calc_metric():

> vars is a table with all channel variables of the enqueued entry

Please elaborate a bit more if i got you wrong.
Cheers!

**Comment by romkazor** [comment]
Oh, thanks, that's all I need. Sorry, my bad.
